POST http://localhost:8080/users/iivanov/accounts/778999007/transactions
Accept: */*
Content-Type: application/json

{
  "from": 778999007,
  "to": 869866773,
  "count": 10.01
}

###

GET http://localhost:8080/users/gkolokolova/accounts/778999007/transactions
Accept: */*
Content-Type: application/json

###

GET http://localhost:8080/users/gkolokolova/accounts/778999007
Accept: */*
Content-Type: application/json

###